Name:           ros-indigo-catkin-pure-python
Version:        0.0.3
Release:        0%{?dist}
Summary:        ROS catkin_pure_python package

Group:          Development/Libraries
License:        BSD
URL:            http://github.com/asmodehn/catkin_pure_python
Source0:        %{name}-%{version}.tar.gz

Requires:       python-devel
Requires:       python-pip
BuildRequires:  git
BuildRequires:  python-devel
BuildRequires:  python-pip
BuildRequires:  ros-indigo-catkin

%description
Catkin macros to allow using pure python packages in usual catkin workspaces
with normal python workflow.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Thu Apr 07 2016 AlexV <asmodehn@gmail.com> - 0.0.3-0
- Autogenerated by Bloom

* Thu Apr 07 2016 AlexV <asmodehn@gmail.com> - 0.0.2-2
- Autogenerated by Bloom

* Wed Apr 06 2016 AlexV <asmodehn@gmail.com> - 0.0.2-1
- Autogenerated by Bloom

